---
services:
  s3:
    image: "minio/minio"
    ports:
      - "4567:9000"
    environment:
      MINIO_ROOT_USER: AAAAAAAAAAAAAAAAAAAA
      MINIO_ROOT_PASSWORD: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    volumes:
      - ./tmp/s3:/data
    command:
      - server
      - /data
# app:
#   build: .
#   image: fanlin
#   ports:
#     - "3001:3000"
#   volumes:
#     - ./img:/var/lib/fanlin/img
#     - ./cmd/fanlin/sample-conf-container.json:/etc/fanlin.json
